optim: adam
log_interval: 1
num_att_plot: 0
init: xavier_uniform
max_epoch: 200
batch_type: folded
batch_size: 16
iterator_type: chunk
chunk_length: 32000
num_workers: 4
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 0
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
N_per_mixture: 2 # number of outputs for each mixture, 4 in paper
M_per_MoM: 4 # double of N_per_mixture when MOM
ratio_supervised: 0.2 # p supervised data for Semi-supervised training, See in Sec 3.3
SNR_max: 30 # in Equation 2
#bs_limit_per_gpu: 2
enh: tasnet
enh_conf:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    num_spk: 4 # double of N_per_mixture
    norm_type: gLN
    causal: False
    mask_nonlinear: relu
