init: xavier_uniform
max_epoch: 150
batch_type: folded
batch_size:  16
num_workers: 8
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1

enh: long_seq
enh_conf:
    model: GlobalATT
    loss_type: magnitude
    n_fft: 512
    window_size: 512
    hop_length: 256
    feature_dim: 256
    hidden_dim: 512
    layer: 3
    block_size: 200
    bidirectional: true
    mask: relu
    stitching_loss: true
    dropout: 0.2

# optim: adam
# optim_conf:
#     eps: 1.0e-08
#     weight_decay: 1.0e-8
#     lr: 0.005
# scheduler: warmuplr
# scheduler_conf:
#     warmup_steps: 10000
   
optim: adam
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-8

scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.9
    patience: 1
