init: xavier_uniform
max_epoch: 150
batch_type: folded
batch_size:  16
num_workers: 0

patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1

optim: adam
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    # weight_decay: 1.0e-8
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.9
    patience: 1

enh: long_seq
enh_conf:
    loss_type: snr
    n_fft: 512
    window_size: 512
    hop_length: 256
    block_size: 150
    model: GlobalTransformer
    feature_dim: 256
    num_head: 4
    att_ff: 256
    layer: 4
    dropout: 0.1
    mask: relu
    stitching_loss: false


    
