init: xavier_uniform
max_epoch: 150
batch_type: folded
batch_size:  16
num_workers: 8
accum_grad: 1

patience: 15
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - snr
    - max
-   - valid
    - snr_75_100
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

enh: long_seq
enh_conf:
    loss_type: snr
    n_fft: 512
    window_size: 512
    hop_length: 256
    block_size: 150
    model: LocalTransformer
    feature_dim: 256
    num_head: 4
    att_ff: 1024
    layer: 10
    dropout: 0.1
    mask: relu
    stitching_loss: false

    
