optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size: 1
num_workers: 4
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 0
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
enh: tasnet_ctx
enh_conf:
    enc_dim: 256
    N: 512
    L: 16
    B: 128
    H: 512
    P: 3
    X: 5
    R: 3
    num_spk: 2
    norm_type: gLN
    causal: False
    mask_nonlinear: relu
