optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size: 4
num_workers: 4
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 0
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
enh: tasnet_ctx
enh_conf:
    N: 512
    L: 16
    B: 128
    H: 512
    P: 3
    X: 8
    R: 3
    num_spk: 2
    norm_type: gLN
    causal: False
    mask_nonlinear: relu
    predict_noise: true

ctx_mode: joint_train
ctx_factor: 0.8
ctx_model_conf:
    fs: 8k
    hop_length: 64
    n_fft: 256
    dropout: 0.0
    me_layer: 2
    se_layer: 1 
    hidden: 512
    num_spk: 2
